///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class BusListResponseData {
/*
{
  "bus_id": "1",
  "bus_no": "TN11AA2222",
  "bus_name": "bus1"
}
*/

  String? busId;
  String? busNo;
  String? busName;

  BusListResponseData({
    this.busId,
    this.busNo,
    this.busName,
  });
  BusListResponseData.fromJson(Map<String, dynamic> json) {
    busId = json['bus_id']?.toString();
    busNo = json['bus_no']?.toString();
    busName = json['bus_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bus_id'] = busId;
    data['bus_no'] = busNo;
    data['bus_name'] = busName;
    return data;
  }
}

class BusListResponse {
/*
{
  "message": "Success",
  "data": [
    {
      "bus_id": "1",
      "bus_no": "TN11AA2222",
      "bus_name": "bus1"
    }
  ]
}
*/

  String? message;
  List<BusListResponseData?>? data;

  BusListResponse({
    this.message,
    this.data,
  });
  BusListResponse.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <BusListResponseData>[];
      v.forEach((v) {
        arr0.add(BusListResponseData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
