///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///


///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginRequestBody {
/*
{
  "username": "manivannan@dev-bee.com",
  "password": "46wjdi",
  "role": "Driver"
}
*/

  String? username;
  String? password;
  String? role;

  LoginRequestBody({
    this.username,
    this.password,
    this.role,
  });
  LoginRequestBody.fromJson(Map<String, dynamic> json) {
    username = json['username']?.toString();
    password = json['password']?.toString();
    role = json['role']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['username'] = username;
    data['password'] = password;
    data['role'] = role;
    return data;
  }
}



class LoginResponseData {
/*
{
  "id": "44",
  "token": "MwMQOAOQOQ",
  "role": "Driver",
  "employee_name": "Manivannan ",
  "gender": "Male",
  "employee_id": "D-001",
  "employee_image": "",
  "fcm_password": "Dx46ibMj",
  "department": "",
  "designation": ""
}
*/

  String? id;
  String? token;
  String? role;
  String? employeeName;
  String? gender;
  String? employeeId;
  String? employeeImage;
  String? fcmPassword;
  String? department;
  String? designation;

  LoginResponseData({
    this.id,
    this.token,
    this.role,
    this.employeeName,
    this.gender,
    this.employeeId,
    this.employeeImage,
    this.fcmPassword,
    this.department,
    this.designation,
  });
  LoginResponseData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    token = json['token']?.toString();
    role = json['role']?.toString();
    employeeName = json['employee_name']?.toString();
    gender = json['gender']?.toString();
    employeeId = json['employee_id']?.toString();
    employeeImage = json['employee_image']?.toString();
    fcmPassword = json['fcm_password']?.toString();
    department = json['department']?.toString();
    designation = json['designation']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['token'] = token;
    data['role'] = role;
    data['employee_name'] = employeeName;
    data['gender'] = gender;
    data['employee_id'] = employeeId;
    data['employee_image'] = employeeImage;
    data['fcm_password'] = fcmPassword;
    data['department'] = department;
    data['designation'] = designation;
    return data;
  }
}

class LoginResponse {
/*
{
  "status": 200,
  "message": "Successfully Logged In",
  "data": {
    "id": "44",
    "token": "MwMQOAOQOQ",
    "role": "Driver",
    "employee_name": "Manivannan ",
    "gender": "Male",
    "employee_id": "D-001",
    "employee_image": "",
    "fcm_password": "Dx46ibMj",
    "department": "",
    "designation": ""
  }
}
*/

  int? status;
  String? message;
  LoginResponseData? data;

  LoginResponse({
    this.status,
    this.message,
    this.data,
  });
  LoginResponse.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
    data = (json['data'] != null) ? LoginResponseData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
