///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SchoolListResponseData {
/*
{
  "id": "1",
  "school_id": "1",
  "base_url": "\"http://localhost/smart-school/\""
}
*/

  String? id;
  String? schoolId;
  String? baseUrl;

  SchoolListResponseData({
    this.id,
    this.schoolId,
    this.baseUrl,
  });
  SchoolListResponseData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    schoolId = json['school_id']?.toString();
    baseUrl = json['base_url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['school_id'] = schoolId;
    data['base_url'] = baseUrl;
    return data;
  }
}

class SchoolListResponse {
/*
{
  "message": "Success",
  "data": [
    {
      "id": "1",
      "school_id": "1",
      "base_url": "\"http://localhost/smart-school/\""
    }
  ]
}
*/

  String? message;
  List<SchoolListResponseData?>? data;

  SchoolListResponse({
    this.message,
    this.data,
  });
  SchoolListResponse.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <SchoolListResponseData>[];
      v.forEach((v) {
        arr0.add(SchoolListResponseData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
